#ifndef __GUI_H
#define __GUI_H

#include <Windows.h>
#include "structs.h"
#include "admin.h"
#include "coach.h"
#include "user.h"

#define LOGINWINDOW_CLASS_NAME "VLSMB_FMS_CLASS"
#define ADMINWINDOW_CLASS_NAME "VLSMB_FMS_ADMIN"
#define SCANFWINDOW_CLASS_NAME "VLSMB_WIN_SCANF" 
#define COACHWINDOW_CLASS_NAME "VLSMB_FMS_COACH"
#define USERWINDOW_CLASS_NAME  "VLSMB_FMS_USER"

// 注册控件标识
#define IDC_EDIT_USERNAME 0x1001
#define IDC_EDIT_PASSWORD 0x1002
#define IDC_BTN_REGISTER 0x1003
#define IDC_BTN_LOGIN    0x1004
#define IDC_BTN_SWITCH_LOGIN_REGISTER 0x1005
#define IDC_RADIO_LOGIN_ADMIN 0x1006
#define IDC_RADIO_LOGIN_COACH 0x1007
#define IDC_RADIO_LOGIN_USER 0x1008
#define IDC_EDIT_PHONE 0x1009

// 控制台控件
#define IDC_EDIT_PRINTF 0x100A

// 管理员控制控件标识
#define IDC_MENU_ADMIN_SYSMANAGE 0x100B
#define IDC_MENU_ADMIN_LOGOUT 0x100C
#define IDC_MENU_ADMIN_CHANGEPWD 0x100D
#define IDC_MENU_ADMIN_CHANGECOACHPWD 0x100E
#define IDC_MENU_ADMIN_DATABACKUP	0x100F
#define IDC_MENU_ADMIN_DATARESTORE 0x1010
#define IDC_MENU_ADMIN_COURSETYPE 0x1011
#define IDC_MENU_ADMIN_COURSETYPE_CREATE 0x1012
#define IDC_MENU_ADMIN_COURSETYPE_UPDATE 0x1013
#define IDC_MENU_ADMIN_COURSETYPE_DELETE 0x1014
#define IDC_MENU_ADMIN_COURSETYPE_SHOW 0x104D
#define IDC_MENU_ADMIN_COACH 0x1015
#define IDC_MENU_ADMIN_COACH_CREATE 0x1016
#define IDC_MENU_ADMIN_COACH_UPDATE 0x1017
#define IDC_MENU_ADMIN_COACH_DELETE 0x1018
#define IDC_MENU_ADMIN_COACH_SHOWALL 0x103F
#define IDC_MENU_ADMIN_COACH_SHOWJUDGE 0x1019
#define IDC_MENU_ADMIN_COACH_MARKJUDGE 0x101A
#define IDC_MENU_ADMIN_COURSE 0x101B
#define IDC_MENU_ADMIN_COURSE_CREATE 0x101C
#define IDC_MENU_ADMIN_COURSE_UPDATE 0x101D
#define IDC_MENU_ADMIN_COURSE_DELETE 0x101E
#define IDC_MENU_ADMIN_COACHCOURSEREL_ADD 0x101F
#define IDC_MENU_ADMIN_COACHCOURSEREL_DELETE 0x1020
#define IDC_MENU_ADMIN_SEARCH 0x1021
#define IDC_MENU_ADMIN_SEARCH_SHOWCOURSE 0x1022
#define IDC_MENU_ADMIN_SEARCH_SEARCHCOURSE 0x1023
#define IDC_MENU_ADMIN_SEARCH_SHOWUSER 0x1024
#define IDC_MENU_ADMIN_SEARCH_SEARCHUSER 0x1025
#define IDC_MENU_ADMIN_SORT 0x1026
#define IDC_MENU_ADMIN_SORT_COURSE 0x1027
#define IDC_MENU_ADMIN_SORT_USER 0x1028
#define IDC_MENU_ADMIN_COUNT 0x1029
#define IDC_MENU_ADMIN_COUNT_COURSE 0x102A
#define IDC_MENU_ADMIN_COUNT_COURSEBYID 0x102B
#define IDC_MENU_ADMIN_COUNT_COACH 0x102C
#define IDC_MENU_ADMIN_COUNT_COACHBYID 0x102D
#define IDC_MENU_ADMIN_COUNT_USER 0x102E
#define IDC_MENU_ADMIN_COUNT_USERBYID 0x102F

// 输入控件的标识
#define IDC_EDIT_WINSCANF 0x1030
#define IDC_BTN_WINSCANF 0x1031

// 教练控制控件标识
#define IDC_MENU_COACH_COURSETYPE_ADD 0x1032
#define IDC_MENU_COACH_COURSETYPE_DELETE 0x1033
#define IDC_MENU_COACH_SEARCH_COURSE_SHOW 0x1034
#define IDC_MENU_COACH_SEARCH_COURSE_SEARCH 0x1035
#define IDC_MENU_COACH_SEARCH_USER_SHOW 0x1036
#define IDC_MENU_COACH_SEARCH_USER_SEARCH 0x1037
#define IDC_MENU_COACH_SORT_COURSE 0x1038
#define IDC_MENU_COACH_SORT_USER 0x1039
#define IDC_MENU_COACH_COUNT_COURSETYPE 0x103A
#define IDC_MENU_COACH_COUNT_COURSETYPEBYID 0x103B
#define IDC_MENU_COACH_COUNT_USERCOURSE 0x103C
#define IDC_MENU_COACH_COUNT_USERCOURSEBYID 0x103D
#define IDC_MENU_COACH_SYS_CHANGEPWD 0x103E
// 0x103F已经使用过
#define IDC_MENU_COACH_SYS_LOGOUT 0x1040

// 用户控制控件标识
#define IDC_MENU_USER_SYS_CHANGEINFO 0x1041
#define IDC_MENU_USER_SYS_CHANGEPWD 0x1042
#define IDC_MENU_USER_SYS_LOGOUT 0x1043
#define IDC_MENU_USER_COURSE_ADD 0x1044
#define IDC_MENU_USER_COURSE_DELETE 0x1045
#define IDC_MENU_USER_SEARCH_SHOWCOURSE 0x1046
#define IDC_MENU_USER_SEARCH_SEARCHCOURSE 0x1047
#define IDC_MENU_USER_SORT_COURSE 0x1048
#define IDC_MENU_USER_COUNT_COURSETYPE 0x1049
#define IDC_MENU_USER_COUNT_COURSETYPEBYID 0x104A
#define IDC_MENU_USER_COUNT_COACH 0x104B
#define IDC_MENU_USER_COUNT_COACHBYID 0x104C
// 0x104D已经使用过

// 显示登录窗口
int WINAPI showLoginWindow();

// 显示管理员控制台
int WINAPI showAdminDashboard();

// 显示教练控制台
int WINAPI showCoachDashboard();

// 显示学员控制台
int WINAPI showUserDashboard();

// 窗口接收输入（仅支持一个数据）
bool winScanf(HWND hParent, const char* title, const char* format, void* p);

#endif // !__GUI_H